CodigoFuente/Finanzas.App/Controllers/SimulacionController.cs
using Finanzas.App.Services;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Finanzas.App.Controllers
{
    public class SimulacionController : Controller
    {
        // GET: Ahorro
        [HttpGet]
        public ActionResult Index(long? id)
        {
            CuentaService cs = new CuentaService();
            Models.View.Cuenta model = null;
            if (id.HasValue)
                model = cs.GetCuenta(User.Identity.GetUserId<long>(), id.Value, esSimulacion: true);
            if (model == null)
                return View(cs.GetCuentas(User.Identity.GetUserId<long>(), true));
            else
                return View("IndexSimulacion", model);
        }


        [HttpGet]
        public ActionResult CrearSimulacion()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CrearSimulacion(Models.Binding.Cuenta cuenta)
        {
            if (!ModelState.IsValid)
                return View(cuenta);
            CuentaService cs = new CuentaService();
            long Id = cs.AgregarCuenta(User.Identity.GetUserId<long>(), cuenta, true);
            return RedirectToAction("Index", new { id = Id });
            //redirect to Cuenta-> id cuenta
        }
        [HttpGet]
        public ActionResult CrearMovimiento(long Id)//id de la cuenta
        {
            return View(new Models.Binding.Movimiento()
            {
                CuentaId = Id
            });
        }
        [HttpPost]
        public ActionResult CrearMovimiento(Models.Binding.Movimiento model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            CuentaService cs = new CuentaService();
            if (cs.AgregarMovimiento(User.Identity.GetUserId<long>(), model))
                return RedirectToAction("Index", new { Id = model.CuentaId });
            else
            {
                ModelState.AddModelError("Error", "No se pudo agregar el movimiento, intentelo más tarde");
                return View(model);
            }
        }
        [HttpGet]
        public ActionResult CambiarTea(long Id)//id de la cuenta
        {
            return View(new Models.Binding.TEA()
            {
                CuentaId = Id
            });
        }
        [HttpPost]
        public ActionResult CambiarTea(Models.Binding.TEA model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            CuentaService cs = new CuentaService();
            if (cs.CambiarTEA(User.Identity.GetUserId<long>(), model))
                return RedirectToAction("Index", new { Id = model.CuentaId });
            else
            {
                ModelState.AddModelError("Error", "No se pudo cambiar la TEA, intentelo más tarde");
                return View(model);
            }
        }
        [HttpPost]
        public ActionResult EliminarSimulacion(long cuentaId)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Index");
            }
            CuentaService cs = new CuentaService();
            cs.EliminarCuenta(User.Identity.GetUserId<long>(), cuentaId);
            return RedirectToAction("Index");
        }
        public JsonResult CalcularHastaFecha(long cuentaId, DateTime? fecha)
        {
            if (!ModelState.IsValid || !fecha.HasValue)
            {
                if (!fecha.HasValue)
                    ModelState.AddModelError("Fecha", "Parámetro no ingresado");
                List<string> list = new List<string>();
                foreach (ModelState modelState in ViewData.ModelState.Values)
                {
                    foreach (ModelError error in modelState.Errors)
                    {
                        list.Add(error.ErrorMessage);
                    }
                }
                return Json(new Helpers.JSONResponse()
                {
                    status = "Fail",
                    errors = list
                });
            }
            CuentaService cs = new CuentaService();
            double ans = cs.RecalcularHastaFecha(User.Identity.GetUserId<long>(), cuentaId, fecha.Value);
            if (ans == -1)
            {
                List<string> list = new List<string>();
                list.Add("Datos No Válidos");
                return Json(new Helpers.JSONResponse()
                {
                    status = "Fail",
                    errors = list
                });
            }
            else
            {
                return Json(new Helpers.JSONResponse()
                {
                    status = "Ok",
                    information = ans.ToString()
                });
            }
        }
    }
}

CodigoFuente/Finanzas.App/Views/Simulacion/CambiarTea.cshtml
@using Finanzas.Models.Binding
@model TEA
@{
    ViewBag.Title = "Cambiar TEA";
}


<h2 class="col-sm-6">Cambiar TEA(Tasa Efectiva Anual)</h2>
<a class="btn btn-link col-sm-2 col-sm-offset-4" href="@Url.Action("Index","Simulacion",new { Id = Model.CuentaId})"><i class="fa fa-arrow-left"></i> Regresar</a>

<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-content">
                @using (Html.BeginForm("CambiarTea", "Simulacion", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                {

                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div>
                        <p>
                            &nbsp;
                        </p>
                    </div>
                    @Html.HiddenFor(m => m.CuentaId)
                    <div class="form-group">
                        @Html.LabelFor(m => m.Fecha, new { @class = "col-sm-2 control-label" })
                        <div class="col-sm-10">
                            @Html.TextBoxFor(m => m.Fecha, new { @class = "form-control", @type = "date" })
                            @Html.ValidationMessageFor(m => m.Fecha, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.tea, new { @class = "col-sm-2 control-label" })
                        <div class="col-sm-10">
                            <div class="input-group m-b">
                                @Html.TextBoxFor(m => m.tea, new { @class = "form-control" })
                                <span class="input-group-addon">%</span>
                            </div>
                            @Html.ValidationMessageFor(m => m.tea, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.Descripcion, new { @class = "col-sm-2 control-label" })
                        <div class="col-sm-10">
                            @Html.TextAreaFor(m => m.Descripcion, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.Descripcion, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-2 col-sm-offset-10">
                            <button class="btn btn-block btn-primary" type="submit">Cambiar TEA</button>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

CodigoFuente/Finanzas.App/Views/Simulacion/CrearMovimiento.cshtml
@using Finanzas.Models.Binding
@model Movimiento
@{
    ViewBag.Title = "Crear Movimiento";
}


<h2 class="col-sm-6">Crear Movimiento</h2>
<a class="btn btn-link col-sm-2 col-sm-offset-4" href="@Url.Action("Index","Simulacion",new { Id = Model.CuentaId})"><i class="fa fa-arrow-left"></i> Regresar</a>

<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
        </div>
        <div class="ibox-content">
            @using (Html.BeginForm("CrearMovimiento", "Simulacion", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div>
                    <p>
                        &nbsp;
                    </p>
                </div>
                    <input type="hidden" name="CuentaId" value="@Model.CuentaId" />
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Fecha de Transacción</label>
                        <div class="col-sm-10">
                            <input type="date" class="form-control" name="Fecha" />
                            @Html.ValidationMessageFor(m => m.Fecha, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Tipo de Transacción</label>
                        <div class="col-sm-10">
                            <div class="i-checks"><label> <input type="radio" value="true" name="Retiro"> <i></i> Retiro </label></div>
                            <div class="i-checks"><label> <input type="radio" checked="" value="false" name="Retiro"> <i></i> Depósito </label></div>
                            @Html.ValidationMessageFor(m => m.Retiro, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Monto de la Transacción</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" name="Monto" />
                            @Html.ValidationMessageFor(m => m.Monto, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Monto Descontado</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" name="MonDescuento" />
                            @Html.ValidationMessageFor(m => m.MonDescuento, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Descripción</label>
                        <div class="col-sm-10">
                            <textarea class="form-control" name="Descripcion"></textarea>
                            @Html.ValidationMessageFor(m => m.Descripcion, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-3 col-sm-offset-9">
                            <button class="btn btn-block btn-primary" type="submit">Agregar Movimiento</button>
                        </div>
                    </div>
            }
        </div>
    </div>
</div>
</div>

CodigoFuente/Finanzas.App/Views/Simulacion/CrearSimulacion.cshtml
@using Finanzas.Models.Binding
@model Cuenta
@{
    ViewBag.Title = "Crear Simulacion";
}

<h2>Crear Simulación</h2>

<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <!--<div class="ibox-title">
                <h5>Crear Cuenta</h5>
                <div class="ibox-tools">
                    <a class="collapse-link">
                        <i class="fa fa-chevron-up"></i>
                    </a>
                    <a class="close-link">
                        <i class="fa fa-times"></i>
                    </a>
                </div>
            </div>-->
            <div class="ibox-content">
                @using (Html.BeginForm("CrearSimulacion", "Simulacion", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                {

                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div>
                        <p>
                            &nbsp;
                        </p>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.FechaInicio, new { @class = "col-sm-2 control-label" })
                        <div class="col-sm-10">
                            @Html.TextBoxFor(m => m.FechaInicio, new { @class = "form-control", @type = "date" })
                            @Html.ValidationMessageFor(m => m.FechaInicio, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(m => m.Monto, new { @class = "col-sm-2 control-label" })
                        <div class="col-sm-10">
                            @Html.TextBoxFor(m => m.Monto, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.Monto, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.TEA, new { @class = "col-sm-2 control-label" })
                        <div class="col-sm-10">
                            <div class="input-group m-b">
                                @Html.TextBoxFor(m => m.TEA, new { @class = "form-control" })
                                <span class="input-group-addon">%</span>
                            </div>
                            @Html.ValidationMessageFor(m => m.TEA, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.Descripcion, new { @class = "col-sm-2 control-label" })
                        <div class="col-sm-10">
                            @Html.TextAreaFor(m => m.Descripcion, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.Descripcion, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-2 col-sm-offset-10">
                            <button class="btn btn-block btn-primary" type="submit">Crear Cuenta</button>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

CodigoFuente/Finanzas.App/Views/Simulacion/Index.cshtml
@using Finanzas.Models.View
@model Cuentas
@{
    ViewBag.Title = "Mis Simulaciones";
}

<h2>Simulaciones</h2>

<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Se visualizan las útlimas simulaciones realizadas</h5>
                <div class="ibox-tools">
                    <a class="collapse-link">
                        <i class="fa fa-chevron-up"></i>
                    </a>
                    <a class="close-link">
                        <i class="fa fa-times"></i>
                    </a>
                </div>
            </div>
            <div class="ibox-content">
                <input type="text" class="form-control input-sm m-b-xs" id="filter" placeholder="Search in table">
                <table class="cuentas table table-stripped" data-page-size="10" data-filter=#filter>
                    <thead>
                        <tr>
                            <th>Fecha Inicio</th>
                            <th>Monto Última Transacción</th>
                            <th>Descripcion</th>
                            <th colspan="2">Opciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.Ahorros)
                        {
                            <tr>

                                <td>@item.FechaInicio.ToString("dd - MM - yyyy")</td>
                            
                                <td>@item.Monto</td>
                                <td>@item.Descripcion</td>
                                <td><a href="@Url.Action("Index", "Simulacion", new { id = item.id })">Ver  </a></td>
                                <td>
                                    @using (Html.BeginForm("EliminarSimulacion", "Simulacion", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                                    {
                                        @Html.AntiForgeryToken()
                                        <input type="hidden" name="cuentaId" value="@item.id" />
                                        <button class="btn-link" type="submit"><a>Eliminar</a></button>
                                    }
                                </td>

                            </tr>
                        }

                    </tbody>
                    <tfoot>
                        <tr>
                            <td colspan="5">
                                <ul class="pagination pull-right"></ul>
                            </td>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
</div>


@section scripts {
    <script>

        $(document).ready(function () {

            $('.cuentas').footable();

        });
    </script>
}

CodigoFuente/Finanzas.App/Views/Simulacion/IndexSimulacion.cshtml
@using Finanzas.Models.View
@model Cuenta
@{
    ViewBag.Title = "Simulacion";
}
<div class="col-sm-12">

    <h2 class="col-sm-3">Cuenta de Ahorro</h2>

    <a class="btn btn-info col-sm-offset-4 col-sm-2" href="@Url.Action("CambiarTea","Simulacion",new { Id = Model.id})">Cambiar Tea</a>
    <a class="btn btn-info col-sm-offset-1 col-sm-2" href="@Url.Action("CrearMovimiento","Simulacion",new { Id = Model.id})">Agregar Movimiento</a>
    <br />
    <br />
    <hr />
    <div>
        <h3>
            Resumen de la cuenta
        </h3>
    </div>

    <table class="table table-responsive table-bordered table-hover table-striped">
        <thead>
            <tr>
                <th>Fecha de Inicio</th>
                <th>Monto de la cuenta</th>
                <th>Monto Actual</th>
                <th>Descripcion</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td> @Model.FechaInicio.ToString("dd/MM/yyyy")    </td>
                <td>    S./ @Model.Monto.ToString("0.00")       </td>
                <td>    S./ @Model.MontoActual.ToString("0.00") </td>
                <td>@Model.Descripcion</td>
            </tr>
        </tbody>
    </table>

    <div>
        <h3>
            Resumen de movimientos
        </h3>
    </div>
    <table class="table table-responsive table-bordered table-hover table-striped">
        <thead>
            <tr>
                <th>Fecha</th>
                <th>Monto del movimiento</th>
                <th>Descripción</th>
            </tr>
        </thead>
        @foreach (var item in Model.Movimientos)
        {
            <tr>
                <td>@item.Fecha.ToString("dd/MM/yyyy")</td>
                <td>@(item.Monto != 0 ? "S/. " + item.Monto.ToString("0.00") : "Cambio de TEA: " + item.TEA.Value * 100 + "%")</td>
                <td>@item.Descripcion</td>
            </tr>
        }
        @if (Model.Movimientos.Count > 0)
        {
            <tr>
                <td>@Model.Movimientos[Model.Movimientos.Count - 1].Fecha.ToString("dd/MM/yyyy")</td>
                <td colspan="2" class="text-center">@("TEA inicial: " + Model.Movimientos[Model.Movimientos.Count - 1].TEA.Value * 100 + "%")</td>
            </tr>
        }
    </table>
</div>

@if (!Model.FechaFin.HasValue)
{
    <br />
    <hr />
    <br />
    <h2 id="calculoSimulacion" class="col-sm-offset-2 ">Calcular Hasta fecha:</h2>
    <br />
    using (Html.BeginForm("CalcularHastaFecha", "Simulacion", FormMethod.Post, new { @class = "form-horizontal", role = "form", id = "CalcularForm" }))
    {
        @Html.AntiForgeryToken()
        <div class="form-group">
            <label class="col-sm-2 control-label">Fecha</label>
            <div class="col-sm-4">
                <input id="fechaCalcularForm" type="date" class="form-control" name="fecha" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-2 col-sm-offset-2">
                <button class="btn btn-block btn-primary" type="submit">Calcular</button>
            </div>
        </div>
    }
}
<hr />
<br />
@section js {
    <script>
        $(document).ready(function () {
            var formFin = $("#CalcularForm");
            var __RequestVerificationToken= $("#CalcularForm>input").val();
            var cuentaId = @Model.id;
            $("#CalcularForm").submit(function (event) {
                event.preventDefault();
                var fecha = $("#fechaCalcularForm").val();

                var request = $.ajax({
                    url: "@Url.Action("CalcularHastaFecha", "Simulacion")",
                    method: "POST",
                    data: {
                        cuentaId : cuentaId ,
                        __RequestVerificationToken : __RequestVerificationToken,
                        fecha : fecha
                    },
                    dataType: "json"
                });

                request.done(function( msg ) {
                    if(msg.status == "Ok")
                    {      var number = parseFloat(msg.information);
                    $( "#calculoSimulacion" ).html( "Cálculo hasta fecha: S/. " +  number.toFixed(2) );
                    }
                    else
                        $( "#calculoSimulacion" ).html( "Error: " + msg.errors );
                });

                request.fail(function( jqXHR, textStatus ) {
                    alert( "Error: " + textStatus );
                });
                //alert(fecha);
                //alert(__RequestVerificationToken);
            })
        });
    </script>

}