CodigoFuente/Finanzas.App/Controllers/AhorroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Finanzas.Models.View;
using Finanzas.App.Services;
using Microsoft.AspNet.Identity;

namespace Finanzas.App.Controllers
{
    [Authorize]
    public class AhorroController : Controller
    {
        // GET: Ahorro
        [HttpGet]
        public ActionResult Index(long? id)
        {
            CuentaService cs = new CuentaService();
            Models.View.Cuenta model = null;
            if (id.HasValue)
                model = cs.GetCuenta(User.Identity.GetUserId<long>(), id.Value);
            if (model == null)
                return View(cs.GetCuentas(User.Identity.GetUserId<long>()));
            else
                return View("IndexCuenta", model);
        }


        [HttpGet]
        public ActionResult CrearCuenta()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CrearCuenta(Models.Binding.Cuenta cuenta)
        {
            if (!ModelState.IsValid)
                return View(cuenta);
            CuentaService cs = new CuentaService();
            long Id = cs.AgregarCuenta(User.Identity.GetUserId<long>(), cuenta);
            return RedirectToAction("Index", new { id = Id });
            //redirect to Cuenta-> id cuenta
        }
        [HttpGet]
        public ActionResult CrearMovimiento(long Id)//id de la cuenta
        {
            return View(new Models.Binding.Movimiento()
            {
                CuentaId = Id
            });
        }
        [HttpPost]
        public ActionResult CrearMovimiento(Models.Binding.Movimiento model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            CuentaService cs = new CuentaService();
            if (cs.AgregarMovimientoFinal(User.Identity.GetUserId<long>(), model))
                return RedirectToAction("Index", new { Id = model.CuentaId });
            else
            {
                ModelState.AddModelError("Error", "No se pudo agregar el movimiento, intentelo más tarde");
                return View(model);
            }
        }
        [HttpGet]
        public ActionResult CambiarTea(long Id)//id de la cuenta
        {
            return View(new Models.Binding.TEA()
            {
                CuentaId = Id
            });
        }
        [HttpPost]
        public ActionResult CambiarTea(Models.Binding.TEA model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            CuentaService cs = new CuentaService();
            if (cs.CambiarTEAFinal(User.Identity.GetUserId<long>(), model))
                return RedirectToAction("Index", new { Id = model.CuentaId });
            else
            {
                ModelState.AddModelError("Error", "No se pudo cambiar la TEA, intentelo más tarde");
                return View(model);
            }
        }
        [HttpPost]
        public ActionResult EliminarCuenta(long cuentaId)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Index");
            }
            CuentaService cs = new CuentaService();
            cs.EliminarCuenta(User.Identity.GetUserId<long>(), cuentaId);
            return RedirectToAction("Index");
        }
        [HttpPost]
        public ActionResult FinalizarCuenta(long cuentaId, DateTime fecha)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Index", new { Id = cuentaId });
            }
            CuentaService cs = new CuentaService();
            if (cs.FinalizarCuenta(User.Identity.GetUserId<long>(), cuentaId, fecha))
                return RedirectToAction("Index");
            else
                return RedirectToAction("Index", new { Id = cuentaId });
        }

    }
}

CodigoFuente/Finanzas.App/Controllers/CuentaController.cs
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Finanzas.Identity.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;


namespace Finanzas.App.Controllers
{
    

    [Authorize]
    public class CuentaController : Controller
    {
        #region constants

        private const string XsrfKey = "XsrfId";

        #endregion

        #region member vars

        private CustomUserManager _userManager;

        #endregion

        #region constructors and destructors

        public CuentaController()
        {
        }

        public CuentaController(CustomUserManager userManager)
        {
            UserManager = userManager;
        }

        #endregion

        #region enums

        public enum ManageMessageId
        {
            ChangePasswordSuccess,
            SetPasswordSuccess,
            RemoveLoginSuccess,
            Error
        }

        #endregion

        #region properties

        public CustomUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<CustomUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        private IAuthenticationManager AuthenticationManager
        {
            get
            {
                return HttpContext.GetOwinContext().Authentication;
            }
        }

        #endregion

        #region methods

        [AllowAnonymous]
        public async Task<ActionResult> ConfirmEmail(long? userId, string code)
        {
            if (userId == null || code == null)
            {
                return View("Error");
            }

            var result = await UserManager.ConfirmEmailAsync(userId.GetValueOrDefault(0), code);
            if (result.Succeeded)
            {
                return View("ConfirmEmail");
            }
            AddErrors(result);
            return View();
        }

        //
        // GET: /Account/ForgotPassword

        //
        // POST: /Account/Disassociate
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Disassociate(string loginProvider, string providerKey)
        {
            ManageMessageId? message = null;
            var result = await UserManager.RemoveLoginAsync(long.Parse(User.Identity.GetUserId()), new UserLoginInfo(loginProvider, providerKey));
            if (result.Succeeded)
            {
                var user = await UserManager.FindByIdAsync(long.Parse(User.Identity.GetUserId()));
                await SignInAsync(user, false);
                message = ManageMessageId.RemoveLoginSuccess;
            }
            else
            {
                message = ManageMessageId.Error;
            }
            return RedirectToAction(
                "Manage",
                new
                {
                    Message = message
                });
        }

        //
        // GET: /Account/Manage

        //
        // POST: /Account/ExternalLogin
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult ExternalLogin(string provider, string returnUrl)
        {
            // Request a redirect to the external login provider
            return new ChallengeResult(
                provider,
                Url.Action(
                    "ExternalLoginCallback",
                    "Account",
                    new
                    {
                        ReturnUrl = returnUrl
                    }));
        }

        //
        // GET: /Account/ExternalLoginCallback
        /*[AllowAnonymous]
        public async Task<ActionResult> ExternalLoginCallback(string returnUrl)
        {
            var loginInfo = await AuthenticationManager.GetExternalLoginInfoAsync();
            if (loginInfo == null)
            {
                return RedirectToAction("Login");
            }

            // Sign in the user with this external login provider if the user already has a login
            var user = await UserManager.FindAsync(loginInfo.Login);
            if (user != null)
            {
                await SignInAsync(user, false);
                return RedirectToLocal(returnUrl);
            }
            // If the user does not have an account, then prompt the user to create an account
            ViewBag.ReturnUrl = returnUrl;
            ViewBag.LoginProvider = loginInfo.Login.LoginProvider;
            return View(
                "ExternalLoginConfirmation",
                new ExternalLoginConfirmationViewModel
                {
                    Email = loginInfo.Email
                });
        }*/
        /*
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ExternalLoginConfirmation(ExternalLoginConfirmationViewModel model, string returnUrl)
        {
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Manage");
            }

            if (ModelState.IsValid)
            {
                // Get the information about the user from the external login provider
                var info = await AuthenticationManager.GetExternalLoginInfoAsync();
                if (info == null)
                {
                    return View("ExternalLoginFailure");
                }
                var user = new MyUser
                {
                    UserName = model.Email,
                    Email = model.Email
                };
                var result = await UserManager.CreateAsync(user);
                if (result.Succeeded)
                {
                    result = await UserManager.AddLoginAsync(user.Id, info.Login);
                    if (result.Succeeded)
                    {
                        await SignInAsync(user, false);

                        // For more information on how to enable account confirmation and password reset please visit http://go.microsoft.com/fwlink/?LinkID=320771
                        // Send an email with this link
                        // string code = await UserManager.GenerateEmailConfirmationTokenAsync(user.Id);
                        // var callbackUrl = Url.Action("ConfirmEmail", "Account", new { userId = user.Id, code = code }, protocol: Request.Url.Scheme);
                        // SendEmail(user.Email, callbackUrl, "Confirm your account", "Please confirm your account by clicking this link");

                        return RedirectToLocal(returnUrl);
                    }
                }
                AddErrors(result);
            }

            ViewBag.ReturnUrl = returnUrl;
            return View(model);
        }
        */
        [AllowAnonymous]
        public ActionResult ExternalLoginFailure()
        {
            return View();
        }

        [AllowAnonymous]
        public ActionResult ForgotPassword()
        {
            return View();
        }

        //
        // POST: /Account/ForgotPassword
        /*[HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ForgotPassword(ForgotPasswordViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = await UserManager.FindByNameAsync(model.Email);
                if (user == null || !(await UserManager.IsEmailConfirmedAsync(user.Id)))
                {
                    ModelState.AddModelError("", "The user either does not exist or is not confirmed.");
                    return View();
                }

                // For more information on how to enable account confirmation and password reset please visit http://go.microsoft.com/fwlink/?LinkID=320771
                // Send an email with this link
                // string code = await UserManager.GeneratePasswordResetTokenAsync(user.Id);
                // var callbackUrl = Url.Action("ResetPassword", "Account", new { userId = user.Id, code = code }, protocol: Request.Url.Scheme);		
                // await UserManager.SendEmailAsync(user.Id, "Reset Password", "Please reset your password by clicking <a href=\"" + callbackUrl + "\">here</a>");
                // return RedirectToAction("ForgotPasswordConfirmation", "Account");
            }

            // If we got this far, something failed, redisplay form
            return View(model);
        }
        */
        //
        // GET: /Account/ForgotPasswordConfirmation
        public string test()
        {
            return "si esta autorizado";
        }
        [AllowAnonymous]
        public ActionResult ForgotPasswordConfirmation()
        {
            return View();
        }

        //
        // POST: /Account/LinkLogin
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult LinkLogin(string provider)
        {
            // Request a redirect to the external login provider to link a login for the current user
            return new ChallengeResult(provider, Url.Action("LinkLoginCallback", "Account"), User.Identity.GetUserId());
        }

        //
        // GET: /Account/LinkLoginCallback
        public async Task<ActionResult> LinkLoginCallback()
        {
            var loginInfo = await AuthenticationManager.GetExternalLoginInfoAsync(XsrfKey, User.Identity.GetUserId());
            if (loginInfo == null)
            {
                return RedirectToAction(
                    "Manage",
                    new
                    {
                        Message = ManageMessageId.Error
                    });
            }
            var result = await UserManager.AddLoginAsync(long.Parse(User.Identity.GetUserId()), loginInfo.Login);
            if (result.Succeeded)
            {
                return RedirectToAction("Manage");
            }
            return RedirectToAction(
                "Manage",

CodigoFuente/Finanzas.App/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>

    @Styles.Render("~/Content/css/bootstrap.min.css")
    @Styles.Render("~/Content/font-awesome/css/font-awesome.css")
    <!-- Toastr style -->
    @Styles.Render("~/Content/css/plugins/toastr/toastr.min.css")
    @Styles.Render("~/Content/css/plugins/footable/footable.core.css")
    <!-- Gritter -->
    @Styles.Render("~/Content/js/plugins/gritter/jquery.gritter.css")
    @Styles.Render("~/Content/css/animate.css")
    @Styles.Render("~/Content/css/style.css")
    @RenderSection("css", required: false)
</head>
<body>
    <div id="wrapper">
        <nav class="navbar-default navbar-static-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav metismenu" id="side-menu">
                    <li class="nav-header">
                        <div class="dropdown profile-element">
                            <span>
                            </span>
                            <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                                <span class="clear">
                                    <span class="block m-t-xs">
                                        <strong class="font-bold">@User.Identity.Name</strong>
                                    </span>
                                </span>
                            </a>
                        </div>
                        <div class="logo-element">
                            AV
                        </div>
                    </li>
                    <li class="@(ViewBag.Title == "Mis Cuentas" ? "active" : "")">
                        <a href="@Url.Action("Index", "Ahorro", new {Id ="" })"><i class=" fa fa-dashboard"></i> <span class="nav-label">Mis Cuentas</a>
                    </li>
                    <li class="@(ViewBag.Title == "Crear Cuenta" ? "active" : "")">
                        <a href="@Url.Action("CrearCuenta", "Ahorro")"><i class="fa fa-magic"></i> <span class="nav-label">Nueva Cuenta</a>
                    </li>
                    <li class="@(ViewBag.Title == "Mis Simulaciones" ? "active" : "")">
                        <a href="@Url.Action("Index", "Simulacion", new {Id ="" })"><i class="fa fa-magic"></i> <span class="nav-label">Mis Simulaciones</a>
                    </li>
                    <li class="@(ViewBag.Title == "Crear Simulacion" ? "active" : "")">
                        <a href="@Url.Action("CrearSimulacion", "Simulacion")"><i class="fa fa-magic"></i> <span class="nav-label">Nueva Simulacion</a>
                    </li>
                </ul>
            </div>
        </nav>
        <div id="page-wrapper" class="gray-bg dashbard-1">
            <div class="row border-bottom">
                <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
                    <div class="navbar-header">
                        <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
                        <!--<form role="search" class="navbar-form-custom" action="search_results.html">
                            <div class="form-group">
                                <input type="text" placeholder="Search for something..." class="form-control" name="top-search" id="top-search">
                            </div>
                        </form>-->
                    </div>
                    <ul class="nav navbar-top-links navbar-right">
                        <li>
                            <span class="m-r-sm text-muted welcome-message">Ahorros a la Vista</span>
                        </li>
                        <li>
                            @using (Html.BeginForm("LogOff", "Cuenta", FormMethod.Post, new { style = "padding-left: 20px;" }))
                            {
                                @Html.AntiForgeryToken()
                                <i class="fa fa-sign-out"></i>
                                <button type="submit" class="btn btn-link" style="padding: 20px 5px;">Cerrar Sesión</button>
                            }

                        </li>
                    </ul>
                </nav>
            </div>
            <div class="row  border-bottom white-bg dashboard-header">
                @RenderBody()
            </div>
        </div>
    </div>
    <!-- Mainly scripts -->
    @Scripts.Render("~/Content/js/jquery-2.1.1.js")
    @Scripts.Render("~/Content/js/bootstrap.min.js")
    @Scripts.Render("~/Content/js/bootstrap.min.js")
    @Scripts.Render("~/Content/js/plugins/metisMenu/jquery.metisMenu.js")
    @Scripts.Render("~/Content/js/plugins/slimscroll/jquery.slimscroll.min.js")
    @Scripts.Render("~/Content/js/plugins/footable/footable.all.min.js")
    <!-- Flot -->
    @Scripts.Render("~/Content/js/plugins/flot/jquery.flot.js")
    @Scripts.Render("~/Content/js/plugins/flot/jquery.flot.tooltip.min.js")
    @Scripts.Render("~/Content/js/plugins/flot/jquery.flot.spline.js")
    @Scripts.Render("~/Content/js/plugins/flot/jquery.flot.resize.js")
    @Scripts.Render("~/Content/js/plugins/flot/jquery.flot.pie.js")
    <!-- Peity -->
    @Scripts.Render("~/Content/js/plugins/peity/jquery.peity.min.js")
    @Scripts.Render("~/Content/js/demo/peity-demo.js")
    <!-- Custom and plugin javascript -->
    @Scripts.Render("~/Content/js/inspinia.js")
    <script data-pace-options='{ "ajax": false }' src="@Url.Content("~/Content/js/plugins/pace/pace.min.js")"></script>
    <!-- jQuery UI -->
    @Scripts.Render("~/Content/js/plugins/jquery-ui/jquery-ui.min.js")
    <!-- GITTER -->
    @Scripts.Render("~/Content/js/plugins/gritter/jquery.gritter.min.js")
    <!-- Sparkline -->
    @Scripts.Render("~/Content/js/plugins/sparkline/jquery.sparkline.min.js")
    <!-- Sparkline demo data  -->
    @Scripts.Render("~/Content/js/demo/sparkline-demo.js")
    <!-- ChartJS-->
    @Scripts.Render("~/Content/js/plugins/chartJs/Chart.min.js")
    <!-- Toastr -->
    @Scripts.Render("~/Content/js/plugins/toastr/toastr.min.js")

    <!--<script>
        $(document).ready(function () {
            setTimeout(function () {
                toastr.options = {
                    closeButton: true,
                    progressBar: true,
                    showMethod: 'slideDown',
                    positionClass: 'toast-bottom-right',
                    timeOut: 4000
                };
                toastr.success('Bienvenido @User.Identity.Name', 'Ahorros a la Vista App');
            }, 1000);
        });
    </script>-->

    @RenderSection("scripts", required: false)
    @RenderSection("js", required: false)
</body>
</html>